apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-redis
    release: redis
  name: redis-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis-redis
